language: c
cache: ccache
env:
- ARCH=x64
compiler:
- gcc
os:
- linux
dist: trusty
sudo: false
install:
- npm install coveralls --save-dev
before_script:
 - ccache -s || echo "CCache is not available."
script:
- ./build.sh
after_success:
- npm run coveralls
