version: 1.1.0.{build}

configuration:
- Debug
- Release

environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    VS_VERSION: 11 2012
    VS_PLATFORM: win32

build:
  project: kafkaclient-cpp.sln
  parallel: true
  verbosity: minimal
