version: 1.1.0.{build}

configuration:
- Debug
- Release

environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    VS_VERSION: 11 2012
    VS_PLATFORM: win32

before_build:
- git submodule update --init --recursive
- cmake -H. -BBuild/VS -G "Visual Studio %VS_VERSION%" -DCMAKE_GENERATOR_PLATFORM=%VS_PLATFORM% -DCMAKE_VERBOSE_MAKEFILE=ON -DBUILD_SHARED_LIBS=true -Wno-dev

build:
  project: kafkaclient-cpp.sln
  parallel: true
  verbosity: minimal
